services:
  nest-backend:
    container_name: nest-app
    image: nest-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    env_file: 
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    command: >
      sh -c "npm install && npm run build && yarn start --watch"
    

